---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iapp-deployment-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app-pod

  template:
    metadata:
      labels:
        app: ip-app-pod

    spec:
      containers:
      - name: ip-app-pod
        image: daya28/myapp:v2
        ports:
        - containerPort: 8085
---

apiVersion: v1
kind: Service
metadata:
  name: ip-app-nodeport
spec:
  type: NodePort
  selector:
    app: ip-app-pod
  ports:
  - name: http
    port: 30003
    targetPort: 8085
    nodePort: 30008

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-for-app-pods
spec:
  podSelector:
    matchLabels:
      app: ip-app-pod
  policyTypes:
  - Ingress
  ingress:
    - from:
      - ipBlock:
          cidr:  0.0.0.0/0
      ports:
        - protocol: TCP
          port: 8085 
