---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app

  template:
    metadata:
      labels:
        app: ip-app

    spec:
      containers:
      - name: ip-app
        image: daya28/myapp:v2
        ports:
        - containerPort: 8085
---

apiVersion: v1
kind: Service
metadata:
  name: mynodeport
spec:
  type: NodePort
  selector:
    app: ip-app
  ports:
  - name: http
    port: 30002
    targetPort: 8085
    nodePort: 30005

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-for-pods
spec:
  podSelector:
    matchLabels:
      app: ip-app
  policyTypes:
  - Ingress
  ingress:
    - from:
      - ipBlock:
          cidr:  0.0.0.0/0
      ports:
        - protocol: TCP
          port: 8085 
